menu_list ={'알밥': 'albab', 
'비빔밥': 'bibimbab',
'비빔면': 'bibimnaengmyeon',
'보쌈': 'bossam', 
'불고기': 'bulgogi',
'닭갈비': 'dalg-galbi',
'닭볶음탕': 'dalgbokk-eumtang',
'된장찌개': 'doenjangjjigae', 
'두부김치': 'dubugimchi', 
'갈비': 'galbi', 
'갈비찜': 'galbijjim', 
'갈치구이': 'galchigu-i', 
'김밥': 'gimbab',
'김치볶음밥': 'gimchibokk-eumbab',
'김치전': 'gimchijeon',
'김치찌개': 'gimchijjigae',
'곱창': 'gobchang', 
'계란후라이': 'gyelanhulai', 
'계란찜': 'gyelanjjim', 
'계란말이': 'gyelanmal-i', 
'호박전': 'hobagjeon',
'후라이드치킨': 'hulaideuchikin', 
'훈제오리': 'hunje-oli', 
'잔치국수': 'janchigugsu', 
'장어구이': 'jang-eogu-i', 
'제육볶음': 'jeyugbokk-eum', 
'짜장면': 'jjajangmyeon',
'짬뽕': 'jjamppong', 
'쫄면': 'jjolmyeon', 
'쭈구미볶음': 'jjukkumibokk-eum', 
'조개구이': 'jogaegu-i', 
'족발': 'jogbal', 
'조기구이': 'jogigu-i', 
'주먹밥': 'jumeogbab', 
'칼국수': 'kalgugsu',
'콩국수': 'kong-gugsu', 
'콩나물국밥': 'kongnamulgug',
'라면': 'lamyeon', 
'막국수': 'maggugsu', 
'만두': 'mandu',
'미역국': 'miyeoggug', 
'물회': 'mulhoe', 
'물냉면': 'mulnaengmyeon',
'오징어튀김': 'ojing-eotwigim',
'파스타': 'paseuta',
'피자': 'pija', 
'생선구이': 'saengseonjeon', 
'새우볶음밥': 'saeubokk-eumbab',
'새우튀김': 'saeutwigim', 
'삼겹살': 'samgyeobsal', 
'삼계탕': 'samgyetang', 
'산낙지': 'sannagji', 
'설렁탕': 'seolleongtang', 
'수제비': 'sujebi', 
'순대': 'sundae', 
'순대국밥': 'sundaegugbab',
'탕수육': 'tangsuyug', 
'떡볶이': 'tteogbokk-i', 
'떡국': 'tteoggug', 
'우동': 'udong', 
'양념치킨': 'yangnyeomchikin',
'유부초밥': 'yubuchobab', 
'육회': 'yughoe',
'크림파스타' : 'keulimpaseuta',
'토마토파스타' : 'tomatopaseuta',
'일본식돈까스' : 'japanese_donkkaseu',
'양식돈까스' : 'donkkaseu'}

def find_name(foods):
    en_names = []
    for food in foods:
        try:
            en_name = menu_list[food]
            en_names.append(en_name)
        except KeyError:
            print(food,"은 menu.py에 존재하지 않습니다.")
    return en_names